data1=read.csv('C:/Users/KIIT/Documents/5th Semester/AP Lab G2/XYdata.csv')
data2=read.csv('C:/Users/KIIT/Documents/5th Semester/AP Lab G2/iris.csv')
data1
data2
File=loadWorkbook('C:/Users/KIIT/Documents/5th Semester/AP Lab G2/XYData.csv')
unique(iris[,1 ])
length(unique(iris[,1]))
sapply(iris,class)
names ( iris )
str ( iris )
summary ( iris )
iris [ 1:5, ]
table ( iris $ Species )
range ( iris $ Sepal.Width )
var ( iris $ Sepal.Length )
cov ( iris $ Sepal.Length, iris $Petal.Length )
cor ( iris $ Sepal.Length, iris $Petal.Length )
sd ( iris $ Sepal.Length , na.rm = FALSE )
sd ( iris $ Sepal.Length )
pie ( table ( iris $ Sepal.Length ) )
hist ( iris $ Sepal.Length )
plot ( density ( iris $ Sepal.Length ) )
plot ( iris $ Sepal.Length, iris $ Sepal.Width )
plot ( iris [ , 1 ], iris [ , 2 ] )
plot ( iris )
